package a;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people.proto

public interface infoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:info)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fullname = 1;</code>
   */
  String getFullname();
  /**
   * <code>string fullname = 1;</code>
   */
  com.google.protobuf.ByteString
      getFullnameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();
}
