package a;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people.proto

public interface nameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:name)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string n = 1;</code>
   */
  String getN();
  /**
   * <code>string n = 1;</code>
   */
  com.google.protobuf.ByteString
      getNBytes();
}
