package a;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: people.proto

public final class PeopleProto {
  private PeopleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_name_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_name_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_infoData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_infoData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014people.proto\"%\n\004info\022\020\n\010fullname\030\001 \001(\t" +
      "\022\013\n\003age\030\002 \001(\005\"\021\n\004name\022\t\n\001n\030\001 \001(\t\" \n\010info" +
      "Data\022\024\n\005infoD\030\001 \003(\0132\005.info2%\n\006people\022\033\n\t" +
      "GetPeople\022\005.name\032\005.info\"\000B\025B\013PeopleProto" +
      "P\001\242\002\003RTGb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_info_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_descriptor,
        new String[] { "Fullname", "Age", });
    internal_static_name_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_name_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_name_descriptor,
        new String[] { "N", });
    internal_static_infoData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_infoData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_infoData_descriptor,
        new String[] { "InfoD", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
